# Generated by Django 5.2.14 on 2026-05-21 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField(db_index=True, unique=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('edad', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('imc', models.FloatField()),
                ('clasificacion_imc', models.CharField(blank=True, max_length=50)),
                ('presion_sistolica', models.PositiveSmallIntegerField()),
                ('presion_diastolica', models.PositiveSmallIntegerField()),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField()),
                ('glucosa', models.FloatField()),
                ('colesterol', models.FloatField()),
                ('saturacion_oxigeno', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('antecedentes_familiares', models.BooleanField(default=False)),
                ('fumador', models.BooleanField(default=False)),
                ('consumo_alcohol', models.BooleanField(default=False)),
                ('actividad_fisica', models.CharField(blank=True, max_length=50)),
                ('diagnostico_preliminar', models.CharField(blank=True, max_length=120)),
                ('riesgo_enfermedad', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='bajo', max_length=20)),
                ('fecha_consulta', models.DateField()),
                ('es_critico', models.BooleanField(db_index=True, default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-es_critico', 'apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='LogETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('exitoso', 'Exitoso'), ('error', 'Error')], default='en_proceso', max_length=20)),
                ('archivo_fuente', models.CharField(blank=True, max_length=255)),
                ('registros_extraidos', models.IntegerField(default=0)),
                ('registros_duplicados', models.IntegerField(default=0)),
                ('registros_nulos_corregidos', models.IntegerField(default=0)),
                ('registros_invalidos', models.IntegerField(default=0)),
                ('registros_cargados', models.IntegerField(default=0)),
                ('tiempo_ejecucion', models.FloatField(default=0)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log ETL',
                'verbose_name_plural': 'Logs ETL',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
