# Generated by Django 6.0.6 on 2026-06-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cluster',
            field=models.IntegerField(blank=True, help_text='Cluster asignado por K-Means', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='es_anomalia',
            field=models.BooleanField(default=False, help_text='Detectado como anomalía por Isolation Forest'),
        ),
    ]
